export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';

export const LOGOUT_USER_REQUEST = 'LOGOUT_USER_REQUEST';
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';
export const LOGOUT_USER_FAIL = 'LOGOUT_USER_FAIL';

export const CHECK_USER_AUTHENTICATION_REQUEST =
	'CHECK_USER_AUTHENTICATION_REQUEST';
export const CHECK_USER_AUTHENTICATION_SUCCESS =
	'CHECK_USER_AUTHENTICATION_SUCCESS';
export const CHECK_USER_AUTHENTICATION_FAIL = 'CHECK_USER_AUTHENTICATION_FAIL';

export const FETCH_POPULAR_VIDEOS_REQUEST = 'FETCH_VIDEOS_REQUEST';

export const FETCH_POPULAR_VIDEOS_SUCCESS = 'FETCH_VIDEOS_SUCCESS';
export const FETCH_POPULAR_VIDEOS_FAIL = 'FETCH_VIDEOS_FAIL';
